[package]
name = "standardoc"
description = "CLI for Standardoc — extract, transform and emit documentation from code"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true

[[bin]]
name = "standardoc"
path = "src/main.rs"

[dependencies]
standardoc-core = { workspace = true }
standardoc-lang-rust = { version = "0.1.0", path = "../standardoc-lang-rust" }
standardoc-lang-ts = { version = "0.1.0", path = "../standardoc-lang-ts" }
standardoc-lang-python = { version = "0.1.0", path = "../standardoc-lang-python" }
standardoc-lang-tree-sitter = { version = "0.1.0", path = "../standardoc-lang-tree-sitter" }
serde_json = { workspace = true }

[lints]
workspace = true
