import type { EntryPointKind } from '../explorer/explorer.type';
import type { SymbolRelationKind } from './symbol-details.type';
import s from './symbol-details.module.scss';

export const STANDARDOC_SYMBOL_DETAILS_TAG = 'standardoc-symbol-details';

export const C = {
  details: s.details ?? '',
  headerBar: s['details__header-bar'] ?? '',
  head: s.details__head ?? '',
  nameRow: s['details__name-row'] ?? '',
  name: s.details__name ?? '',
  iconBtn: s['details__icon-btn'] ?? '',
  tags: s.details__tags ?? '',
  tag: s.details__tag ?? '',
  tagKindCallable: s['details__tag--kind-callable'] ?? '',
  tagKindType: s['details__tag--kind-type'] ?? '',
  tagKindValue: s['details__tag--kind-value'] ?? '',
  tagKindModule: s['details__tag--kind-module'] ?? '',
  tagKindMacro: s['details__tag--kind-macro'] ?? '',
  tagVisPublic: s['details__tag--visibility-public'] ?? '',
  tagVisPrivate: s['details__tag--visibility-private'] ?? '',
  tagVisCrate: s['details__tag--visibility-crate'] ?? '',
  tagVisProtected: s['details__tag--visibility-protected'] ?? '',
  location: s.details__location ?? '',
  locationPath: s['details__location-path'] ?? '',
  tabs: s.details__tabs ?? '',
  tab: s.details__tab ?? '',
  tabActive: s['details__tab--active'] ?? '',
  body: s.details__body ?? '',
  empty: s.details__empty ?? '',
  section: s.details__section ?? '',
  sectionTitle: s['details__section-title'] ?? '',
  sectionTitleDoc: s['details__section-title--doc'] ?? '',
  sectionTitleRelations: s['details__section-title--relations'] ?? '',
  sectionTitleEntry: s['details__section-title--entry'] ?? '',
  sectionTitleFields: s['details__section-title--fields'] ?? '',
  sectionTitleMethods: s['details__section-title--methods'] ?? '',
  sectionTitleSource: s['details__section-title--source'] ?? '',
  doc: s.details__doc ?? '',
  docToggle: s['details__doc-toggle'] ?? '',
  relation: s.details__relation ?? '',
  relationHeader: s['details__relation-header'] ?? '',
  relationTitle: s['details__relation-title'] ?? '',
  relationCount: s['details__relation-count'] ?? '',
  relationSpacer: s['details__relation-spacer'] ?? '',
  seeAll: s['details__see-all'] ?? '',
  relationList: s['details__relation-list'] ?? '',
  relationItem: s['details__relation-item'] ?? '',
  relationItemLabel: s['details__relation-item-label'] ?? '',
  relationItemSignature: s['details__relation-item-signature'] ?? '',
  relationItemKind: s['details__relation-item-kind'] ?? '',
  entryPoint: s['details__entry-point'] ?? '',
  entryPointBadge: s['details__entry-point-badge'] ?? '',
  entryPointBadgeBinMain: s['details__entry-point-badge--binary-main'] ?? '',
  entryPointBadgePublicApi: s['details__entry-point-badge--public-api'] ?? '',
  entryPointBadgeFfiExport: s['details__entry-point-badge--ffi-export'] ?? '',
  actions: s.details__actions ?? '',
  action: s.details__action ?? '',
  relationKindCalls: s['details__relation--kind-calls'] ?? '',
  relationKindImports: s['details__relation--kind-imports'] ?? '',
  relationKindUsesType: s['details__relation--kind-uses-type'] ?? '',
  relationKindImplements: s['details__relation--kind-implements'] ?? '',
  relationKindTests: s['details__relation--kind-tests'] ?? '',
  relationKindUsedBy: s['details__relation--kind-used-by'] ?? '',
  relationKindDefined: s['details__relation--kind-defined'] ?? '',
  itemPopup: s['details__item-popup'] ?? '',
  itemPopupName: s['details__item-popup-name'] ?? '',
  itemPopupSignature: s['details__item-popup-signature'] ?? '',
  itemPopupTags: s['details__item-popup-tags'] ?? '',
  subItemChip: s['details__sub-item-chip'] ?? '',
  subItemChipAsync: s['details__sub-item-chip--async'] ?? '',
  subItemChipType: s['details__sub-item-chip--type'] ?? '',
  headerToggle: s['details__header-toggle'] ?? '',
  headerToggleActive: s['details__header-toggle--active'] ?? '',
  markdown: s.details__markdown ?? '',
} as const;

export const RELATION_KIND_CLASS: Record<SymbolRelationKind, string> = {
  calls: C.relationKindCalls,
  usedBy: C.relationKindUsedBy,
  imports: C.relationKindImports,
  importedBy: C.relationKindImports,
  usesTypes: C.relationKindUsesType,
  implements: C.relationKindImplements,
  extends: C.relationKindImplements,
  testedBy: C.relationKindTests,
  definedHere: C.relationKindDefined,
};

export const RELATION_TITLE: Record<SymbolRelationKind, string> = {
  usedBy: 'Used by',
  usesTypes: 'Uses types',
  calls: 'Calls',
  imports: 'Imports',
  importedBy: 'Imported by',
  testedBy: 'Tested by',
  implements: 'Implements',
  extends: 'Extends',
  definedHere: 'Defined here',
};

export const TOP_PER_RELATION = 5;
export const DOC_COLLAPSED_CHARS = 180;

export const entryPointBadgeClass: Record<EntryPointKind, string> = {
  binary_main: C.entryPointBadgeBinMain,
  public_api: C.entryPointBadgePublicApi,
  ffi_export: C.entryPointBadgeFfiExport,
};
