[package]
name = "standardoc-lang-ts"
description = "TypeScript / JavaScript language provider for Standardoc (powered by swc)"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
standardoc-core = { workspace = true }
swc_common = "21.0.1"
swc_ecma_ast = "23.0.0"
swc_ecma_parser = "39.0.0"
swc_ecma_visit = "23.0.0"

[lints]
workspace = true
