use std::fmt::Write;
use std::path::Path;

use super::{SessionRow, SessionsError, SessionsHandle};

/// Exports all sessions (active + superseded) to a single markdown file. The
/// format is the same one the supervisor would feed back into a (future)
/// `session_import` tool — so dumps are a durable backup against schema
/// migrations or accidental DB loss.
///
/// Returns the number of sessions written.
pub fn dump_sessions_to_markdown(
    handle: &SessionsHandle,
    target: &Path,
) -> Result<usize, SessionsError> {
    let rows = handle.list(false)?;
    let body = render_markdown(&rows);
    std::fs::write(target, body)?;
    Ok(rows.len())
}

fn render_markdown(rows: &[SessionRow]) -> String {
    let mut out = String::from(
        "# Standardoc sessions export\n\
         \n\
         Generated by `session_dump_md`. Re-importable by an external tool that\n\
         re-emits each section as a `session_save` call. Order: newest first.\n\
         \n",
    );
    for row in rows {
        // Writes into a `String` are infallible — the `unwrap()` calls
        // below cannot fire (`std::fmt::Write for String` returns Ok always).
        writeln!(out, "## {}\n", row.slug).unwrap();
        writeln!(out, "- id: {}", row.id).unwrap();
        writeln!(out, "- status: {}", row.status.as_str()).unwrap();
        writeln!(out, "- created_at: {}", row.created_at).unwrap();
        if let Some(sup) = &row.supersedes {
            writeln!(out, "- supersedes: {sup}").unwrap();
        }
        out.push('\n');
        out.push_str(&row.body_md);
        if !row.body_md.ends_with('\n') {
            out.push('\n');
        }
        out.push_str("\n---\n\n");
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use super::super::SessionStatus;

    fn fresh_handle() -> (tempfile::TempDir, SessionsHandle) {
        let dir = tempfile::tempdir().unwrap();
        let handle = SessionsHandle::open(dir.path()).unwrap();
        (dir, handle)
    }

    #[test]
    fn render_includes_header_and_separator_per_row() {
        let row = SessionRow {
            id: 1,
            slug: "s1".into(),
            body_md: "body".into(),
            supersedes: None,
            status: SessionStatus::Active,
            created_at: 100,
        };
        let out = render_markdown(&[row]);
        assert!(out.starts_with("# Standardoc sessions export"));
        assert!(out.contains("## s1"));
        assert!(out.contains("- status: active"));
        assert!(out.contains("body"));
        assert!(out.contains("\n---\n"));
    }

    #[test]
    fn render_includes_supersedes_line_when_present() {
        let row = SessionRow {
            id: 2,
            slug: "s2".into(),
            body_md: "body".into(),
            supersedes: Some("s1".into()),
            status: SessionStatus::Active,
            created_at: 200,
        };
        let out = render_markdown(&[row]);
        assert!(out.contains("- supersedes: s1"));
    }

    #[test]
    fn dump_writes_file_and_returns_row_count() {
        let (dir, handle) = fresh_handle();
        handle.save("s1", "first", None).unwrap();
        handle.save("s2", "second", None).unwrap();
        let target = dir.path().join("dump.md");
        let count = dump_sessions_to_markdown(&handle, &target).unwrap();
        assert_eq!(count, 2);
        let body = std::fs::read_to_string(&target).unwrap();
        assert!(body.contains("## s2"));
        assert!(body.contains("## s1"));
    }

    #[test]
    fn dump_on_empty_db_writes_just_the_header() {
        let (dir, handle) = fresh_handle();
        let target = dir.path().join("dump.md");
        let count = dump_sessions_to_markdown(&handle, &target).unwrap();
        assert_eq!(count, 0);
        let body = std::fs::read_to_string(&target).unwrap();
        assert!(body.starts_with("# Standardoc sessions export"));
        assert!(!body.contains("## "));
    }
}
